---
- name: install Apache
  hosts: all
  tasks:
    - name: install httpd package
      package: 
        name: httpd
        state: present
    - name: run service
      service:
        name: httpd
        state: started  
    - name: create index.html file
      copy:
        dest: "/var/www/html/index.html"
        content: "Welcome to my web server"
    - name: open ports
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
...
